---
title: "EHCE Area Trend Analysis"
author: "Jingya Cheng"
date: "2024-01-05"
categories: [code, analysis, trend]
---

# Extreme Heat/Cold Events Area Trend Analysis

```{r, include=FALSE}
library(readr)
library(viridis)
library(tidyverse)
library(sf)
library(gridExtra)
library(RColorBrewer)
library(pscl)
library(reshape2)
library(data.table)
library(broom)
library(DescTools)
```

### Loading the base spatail data set including Counties and States boundaires

```{r}
source_dir <- "./data/"
states_file_path <- file.path(source_dir,
                              "us49_states_geo_tigris.rds")
states_geo <- readRDS(states_file_path)[[1]]
counties_file_path <- file.path(source_dir,
                                "us49_counties_geo_tigris.rds")
counties_geo <- readRDS(counties_file_path)[[1]]
```

### Loading the aggregate extreme events data set

```{r}
dat_path <- file.path(source_dir,
                      "S190_T002_Counties_compiled_admin_geo_ehe_ece_sf_2008_2022.rds")
file_size <- file.info(dat_path)$size
dat <- readRDS(dat_path)[[1]]
```

### Data processing
Filter out Extreme Cold events from May to September each year. 
```{r}
dat_table = dat %>%  st_drop_geometry()
dat_table = dat_table %>% 
  filter(!(event_type == "Extreme Cold Event" & month_numerical %in% 5:9))
```


### Overall area

```{r}
## Overall
county_yearly_area_hectare = dat_table %>%
  dplyr::select(GEOID,NAME, STATE_NAME, year_numerical, event_date, impacted_to_total_ratio) %>%
  distinct() %>%
  group_by(GEOID,NAME, STATE_NAME, year_numerical) %>%
  summarize(avg_impacted_to_total_ratio = mean(impacted_to_total_ratio))

dat_area_all = county_yearly_area_hectare %>% 
  complete(
  year_numerical = 2008:2022,
  fill =  list(avg_impacted_to_total_ratio = 0)
  )

#linear regression and calculate percentage change
lm_area_all <- dat_area_all %>%
  group_by(GEOID, NAME, STATE_NAME) %>%
  do(model = lm(avg_impacted_to_total_ratio~ year_numerical, data = .))

slopes_all <- lm_area_all %>%
  rowwise() %>%
  mutate(slope = coef(model)[["year_numerical"]],
         p_value = summary(model)$coefficients["year_numerical","Pr(>|t|)"],
         r_squared = glance(model)$r.squared)
```

```{r}
hist(slopes_all$p_value)
hist(slopes_all$slope)
hist(slopes_all$r_squared)
```

#### Map

```{r}
#slopes_cut = slopes_all %>% filter(!(p_value > 0.5))
# Merge with geometry data
county_boundaris_catalog_all <- merge(counties_geo,
          slopes_all %>% st_drop_geometry(),
          by.x="GEOID",
          by.y="GEOID",
          all.x = TRUE,
          all.y = TRUE,
          suffix = c("","_sp")) %>% st_as_sf() 
# area all map
p_area_ehce = ggplot() +
  geom_sf(data = county_boundaris_catalog_all,
            aes(fill = slope), color = NA,
            lwd = .1) + 
  scale_fill_distiller(palette = "PuOr", 
                       limits = c(-0.065, 0.065),
                       breaks = c(-0.05, 0, 0.05),
                       ) +
  geom_sf(data = states_geo, fill = NA, color = "grey", size = 0.01, alpha = 0.2) +
  labs(fill = "EHCE Impacted Area Ratio Coefficient") +
  theme_void() + 
  theme(legend.position = "bottom")
p_area_ehce
```

### Extreme Heat Events

```{r}
county_ehe_area_hectare <- dat_table %>%
  filter(event_type == "Extreme Heat Event") %>%
  dplyr::select(GEOID,NAME, STATE_NAME, year_numerical, event_date, impacted_to_total_ratio) %>%
  distinct() %>%
  group_by(GEOID,NAME, STATE_NAME, year_numerical) %>%
  summarize(avg_impacted_to_total_ratio = mean(impacted_to_total_ratio))

dat_area_ehe = county_ehe_area_hectare %>% 
  complete(
  year_numerical = 2008:2022,
  fill =  list(avg_impacted_to_total_ratio = 0)
  )

#linear regression and calculate percentage change
lm_area_ehe <- dat_area_ehe %>%
  group_by(GEOID, NAME, STATE_NAME) %>%
  do(model = lm(avg_impacted_to_total_ratio ~ year_numerical, data = .))

slopes_ehe <- lm_area_ehe %>%
  rowwise() %>%
  mutate(slope = coef(model)[["year_numerical"]],
         p_value = summary(model)$coefficients["year_numerical","Pr(>|t|)"],
         r_squared = glance(model)$r.squared)

```

```{r}
hist(slopes_ehe$p_value)
hist(slopes_ehe$slope)
hist(slopes_ehe$r_squared)
```

#### Map

```{r}
#slopes_ehe_cut = slopes_ehe %>% filter(p_value < 0.05)
# Merge with geometry data
county_boundaris_ehe_catalog <- merge(counties_geo,
          slopes_ehe %>% st_drop_geometry(),
          by.x="GEOID",
          by.y="GEOID",
          all.x = TRUE,
          all.y = TRUE,
          suffix = c("","_sp")) %>% st_as_sf() 
# Area EHE map
p_area_ehe = ggplot() +
  geom_sf(data = county_boundaris_ehe_catalog,
            aes(fill = slope),color = NA,
            lwd = .1) + 
  scale_fill_distiller(palette = "PuOr", 
                       limits = c(-0.085, 0.085)
                       ) +
  geom_sf(data = states_geo, fill = NA, color = "grey", size = 0.5) +
  labs(fill = "EHE Impacted Area Ratio Coefficient") +
  theme_void() + 
  theme(legend.position = "bottom")
p_area_ehe

```

### Extreme Cold Events

```{r}
county_ece_area_hectare <- dat_table %>%
  filter(event_type == "Extreme Cold Event") %>%
  dplyr::select(GEOID,NAME, STATE_NAME, year_numerical, event_date, impacted_to_total_ratio) %>%
  distinct() %>%
  group_by(GEOID,NAME, STATE_NAME, year_numerical) %>%
  summarize(avg_impacted_to_total_ratio = mean(impacted_to_total_ratio))
dat_area_ece = county_ehe_area_hectare %>% 
  complete(
  year_numerical = 2008:2022,
  fill =  list(avg_impacted_to_total_ratio = 0)
  )

#linear regression and calculate percentage change
lm_area_ece <- dat_area_ece %>%
  group_by(GEOID, NAME, STATE_NAME) %>%
  do(model = lm(avg_impacted_to_total_ratio ~ year_numerical, data = .))

slopes_ece <- lm_area_ece %>%
  rowwise() %>%
  mutate(slope = coef(model)[["year_numerical"]],
         p_value = summary(model)$coefficients["year_numerical","Pr(>|t|)"],
         r_squared = glance(model)$r.squared)


```

```{r}
hist(slopes_ece$p_value)
hist(slopes_ece$slope)
hist(slopes_ece$r_squared)
```

#### Map

```{r}
#slopes_ece_cut = slopes_ece %>% filter(p_value < 0.05)
# Merge with geometry data
county_boundaris_ece_catalog <- merge(counties_geo,
          slopes_ece %>% st_drop_geometry(),
          by.x="GEOID",
          by.y="GEOID",
          all.x = TRUE,
          all.y = TRUE,
          suffix = c("","_sp")) %>% st_as_sf() 
# Area ECE map
p_area_ece = ggplot() +
  geom_sf(data = county_boundaris_ece_catalog,
            aes(fill = slope), color = NA,
            lwd = .1) + 
  scale_fill_distiller(palette = "PuOr", 
                       limits = c(-0.071, 0.071)
                       ) +
  geom_sf(data = states_geo, fill = NA, color = "grey", size = 0.5) +
  labs(fill = "ECE Impacted Area Ratio Coefficient") +
  theme_void() + 
  theme(legend.position = "bottom")
p_area_ece
#png("~/Desktop/ehe_ece_data_integration/post/output/area_reg_ece.png",
#    height = 5, width = 7, res = 300, units = "in")
#print(p_area_ece)
#dev.off()
```
