---
title: "EHCE Intensity Trend Analysis"
author: "Jingya Cheng"
date: "2024-01-04"
categories: [code, analysis, trend]
---

# Extreme Heat/Cold Events Intensity Trend Analysis

```{r, include=FALSE}
library(readr)
library(viridis)
library(tidyverse)
library(sf)
library(gridExtra)
library(RColorBrewer)
library(pscl)
library(reshape2)
library(data.table)
library(broom)
```

### Loading the base spatail data set including Counties and States boundaires

```{r}
source_dir <- "./data/"
states_file_path <- file.path(source_dir,
                              "us49_states_geo_tigris.rds")
states_geo <- readRDS(states_file_path)[[1]]
counties_file_path <- file.path(source_dir,
                                "us49_counties_geo_tigris.rds")
counties_geo <- readRDS(counties_file_path)[[1]]
```

### Loading the aggregate extreme events data set

```{r}
dat_path <- file.path(source_dir,
                      "S190_T002_Counties_compiled_admin_geo_ehe_ece_sf_2008_2022.rds")
file_size <- file.info(dat_path)$size
dat <- readRDS(dat_path)[[1]]
st_crs(dat)$epsg
```

### Data processing
Filter out Extreme Cold events from May to September each year. 
```{r}
dat_table = dat %>%  st_drop_geometry()
dat_table = dat_table %>% 
  filter(!(event_type == "Extreme Cold Event" & month_numerical %in% 5:9))
```

### Overall intensity

```{r, warning = FALSE}
## Overall
dat_table$abs_intensity = abs(dat_table$avg_intensity)

county_yearly_intensity <- dat_table %>%
  dplyr::select(GEOID,NAME, STATE_NAME, year_numerical, event_date, abs_intensity) %>%
  distinct() %>%
  group_by(GEOID,NAME, STATE_NAME, year_numerical) %>%
  summarize(mean_intensity = mean(abs_intensity))

dat_intensity_all = county_yearly_intensity %>% complete(
  year_numerical = 2008:2022,
  fill =  list(mean_intensity = 0)
  )

#linear regression and calculate percentage change with standardized average intensity 
lm_intensity_all <- dat_intensity_all %>%
  group_by(GEOID, NAME, STATE_NAME) %>%
  do(model = lm(mean_intensity ~ year_numerical, data = .))

slopes_all <- lm_intensity_all %>%
  rowwise() %>%
  mutate(slope = coef(model)[["year_numerical"]],
         p_value = summary(model)$coefficients["year_numerical","Pr(>|t|)"],
         r_squared = glance(model)$r.squared)

```

```{r}
hist(slopes_all$p_value)
hist(slopes_all$slope)
hist(slopes_all$r_squared)
```

#### Map

```{r, warning = FALSE}
#slopes_cut = slopes_all %>% filter(!(p_value > 0.5))
# Merge with geometry data
county_boundaris_catalog_all <- merge(counties_geo,
          slopes_all %>% st_drop_geometry(),
          by.x="GEOID",
          by.y="GEOID",
          all.x = TRUE,
          all.y = TRUE,
          suffix = c("","_sp")) %>% st_as_sf() 
# Intensity all map
p_int_ehce = ggplot() +
  geom_sf(data = county_boundaris_catalog_all,
            aes(fill = slope), color = NA,
            lwd = .1) + 
  scale_fill_distiller(palette = "PuOr", limits = c(-2.55, 2.55)
                       ) +
  geom_sf(data = states_geo, fill = NA, color = "grey", size = 0.01, alpha = 0.2) +
  labs(fill = "EHCE Intensity Coefficient") +
  theme_void() + 
  theme(legend.position = "bottom")
p_int_ehce
```

### Extreme Heat Events

```{r, warning = FALSE}
county_heat_intensity <- dat_table %>%
  filter(event_type == "Extreme Heat Event") %>%
  dplyr::select(GEOID,NAME, STATE_NAME, year_numerical, event_date, abs_intensity) %>%
  distinct() %>%
  group_by(GEOID,NAME, STATE_NAME, year_numerical) %>%
  summarize(mean_intensity = mean(abs_intensity))

dat_intensity_ehe = county_heat_intensity %>% complete(
  year_numerical = 2008:2022,
  fill =  list(mean_intensity = 0)
  )

## Standardized linear regression
lm_intensity_ehe <- dat_intensity_ehe %>%
  group_by(GEOID, NAME, STATE_NAME) %>%
  do(model = lm(mean_intensity ~ year_numerical, data = .))

slopes_ehe <- lm_intensity_ehe %>%
  rowwise() %>%
  mutate(slope = coef(model)[["year_numerical"]],
         p_value = summary(model)$coefficients["year_numerical","Pr(>|t|)"],
         r_squared = glance(model)$r.squared)

```

```{r}
hist(slopes_ehe$p_value)
hist(slopes_ehe$slope)
hist(slopes_ehe$r_squared)
```

#### Map

```{r, warning = FALSE}
#slopes_ehe_cut = slopes_ehe %>% filter(p_value < 0.05)
# Merge with geometry data
county_boundaris_ehe_catalog <- merge(counties_geo,
          slopes_ehe %>% st_drop_geometry(),
          by.x="GEOID",
          by.y="GEOID",
          all.x = TRUE,
          all.y = TRUE,
          suffix = c("","_sp")) %>% st_as_sf() 
# Intensity EHE map
p_int_ehe = ggplot() +
  geom_sf(data = county_boundaris_ehe_catalog,
            aes(fill = slope),color = NA,
            lwd = .1) + 
  scale_fill_distiller(palette = "PuOr", limit = c(-2.55, 2.55)) +
  geom_sf(data = states_geo, fill = NA, color = "grey", size = 0.5) +
  labs(fill = "EHE Intensity Coefficient") +
  theme_void() + 
  theme(legend.position = "bottom")
p_int_ehe

```

### Extreme Cold Events

```{r, warning = FALSE}
county_cold_intensity <- dat_table %>%
  filter(event_type == "Extreme Cold Event") %>%
  dplyr::select(GEOID,NAME, STATE_NAME, year_numerical, event_date, abs_intensity) %>%
  distinct() %>%
  group_by(GEOID,NAME, STATE_NAME, year_numerical) %>%
  summarize(mean_intensity = mean(abs_intensity))

dat_intensity_ece = county_cold_intensity %>% complete(
  year_numerical = 2008:2022,
  fill =  list(mean_intensity = 0)
  )

lm_intensity_ece <- dat_intensity_ece %>%
  group_by(GEOID, NAME, STATE_NAME) %>%
  do(model = lm(mean_intensity ~ year_numerical, data = .))

slopes_ece <- lm_intensity_ece %>%
  rowwise() %>%
  mutate(slope = coef(model)[["year_numerical"]],
         p_value = summary(model)$coefficients["year_numerical","Pr(>|t|)"],
         r_squared = glance(model)$r.squared)

```

```{r}
hist(slopes_ece$p_value)
hist(slopes_ece$slope)
hist(slopes_ece$r_squared)
```

#### Map

```{r, warning = FALSE}
#slopes_ece_cut = slopes_ece %>% filter(p_value < 0.05)
# Merge with geometry data
county_boundaris_ece_catalog <- merge(counties_geo,
          slopes_ece %>% st_drop_geometry(),
          by.x="GEOID",
          by.y="GEOID",
          all.x = TRUE,
          all.y = TRUE,
          suffix = c("","_sp")) %>% st_as_sf() 
# Intensity ECE map
p_int_ece = ggplot() +
  geom_sf(data = county_boundaris_ece_catalog,
            aes(fill = slope), color = NA,
            lwd = .1) + 
  scale_fill_distiller(palette = "PuOr", limit = c(-2.55, 2.55)) +
  geom_sf(data = states_geo, fill = NA, color = "grey", size = 0.5) +
  labs(fill = "ECE Intensity Coefficient") +
  theme_void() + 
  theme(legend.position = "bottom")
p_int_ece
#png("~/Desktop/ehe_ece_data_integration/post/output/int_reg_ece.png",
#    height = 5, width = 7, res = 300, units = "in")
#print(p_int_ece)
#dev.off()
```
