project:
  type: website

website:
  title: "Extreme Climate Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/clai-group/Confluence_web/tree/main

format:
  html:
    theme: Flatly
    css: styles.css
    grid:
      sidebar-width: 350px

editor: visual

